import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import Footer from '@/components/footer/Footer';

export const metadata: Metadata = {
  title: 'Binder',
  description: 'Generated by create next app',
};

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={pretendard.className} lang="en">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
